# AWS Configuration

# AWS Credentials
aws:
  region: "ap-south-1"  # Change this to your AWS region
  access_key_id: "AKIAVWABJZFQINXAOZNA"    # Add your AWS Access Key ID
  secret_access_key: "+6l6SIhS2vDD0CkI8b6cmwxIK5uKoN+627OeABKq" # Add your AWS Secret Access Key
  # Optional: Use profile instead of access keys
  # profile: "default"  # Uncomment and set your AWS profile name if using profiles

# Analysis Settings
analysis:
  max_workers: 4
  retry_attempts: 3
  retry_delay: 1

# Bucket Configuration
buckets:
  aws-cloudtrail-logs-390844762464-736889dc:
    AWS:
      - prefix: "AWSLogs/390844762464/CloudTrail/ap-south-1/2025/03/"
        compression_ratio: 1.0
